# Generated by Django 5.1 on 2024-08-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='source',
        ),
        migrations.AddField(
            model_name='bus',
            name='destination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='destination_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='source_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='source_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
