# Generated by Django 5.1 on 2024-08-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_bus_arrival_time_remove_bus_departure_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_no',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
