# Generated by Django 5.1 on 2024-08-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_agency_contact_info_agency_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
