# Generated by Django 5.1 on 2024-08-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_agency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking_agency',
        ),
    ]
