# Generated by Django 5.1 on 2024-08-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_agency_address_agency_password_agency_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='agency_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='agency_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
