# Generated by Django 5.1 on 2024-08-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bus_agency_id_bus_agency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='passenger_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
